{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "nuts-discovery.serviceAccountName" . }}
  labels:
{{ include "nuts-discovery.labels" . | indent 4 }}
{{- end -}}
